# Generated by Django 4.1.7 on 2023-04-01 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "delivery_time",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("delivery_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("external_freight_id", models.IntegerField()),
                (
                    "ensurance_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freights",
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
