# Generated by Django 4.1.7 on 2023-04-01 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number_order", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("width", models.DecimalField(decimal_places=2, max_digits=10)),
                ("height", models.DecimalField(decimal_places=2, max_digits=10)),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                ("zip_from", models.IntegerField()),
                ("zip_to", models.IntegerField()),
                (
                    "courier_choice",
                    models.CharField(
                        choices=[
                            ("1", "Pac"),
                            ("2", "Sedex"),
                            ("3", "Jadlog Package"),
                            ("4", "Jadlog Com"),
                        ],
                        default="1",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
